extensions:
  health_check:

receivers:
  zipkin:
  signalfx:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    logLevel: info

service:
  pipelines:
    traces:
      receivers: [ zipkin ]
      processors: [ batch ]
      exporters: [ logging ]
    metrics:
      receivers: [ signalfx ]
      processors: [ batch ]
      exporters: [ logging ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging ]

  extensions: [ health_check ]
